"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class PositionGravityState(object):
    __slots__ = ["data", "gravity"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [[18], [3]]

    def __init__(self):
        self.data = [ 0.0 for dim0 in range(18) ]
        self.gravity = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(PositionGravityState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>18f', *self.data[:18]))
        buf.write(struct.pack('>3f', *self.gravity[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != PositionGravityState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return PositionGravityState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = PositionGravityState()
        self.data = struct.unpack('>18f', buf.read(72))
        self.gravity = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if PositionGravityState in parents: return 0
        tmphash = (0x512376b246b4d410) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if PositionGravityState._packed_fingerprint is None:
            PositionGravityState._packed_fingerprint = struct.pack(">Q", PositionGravityState._get_hash_recursive([]))
        return PositionGravityState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", PositionGravityState._get_packed_fingerprint())[0]

